### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by osukaa**
Update eslintrc to eslintrc.json.
Update travis.yml to node v4 and v6.

### CODE REVIEW

**Comment by osukaa** [comment]
Definitely, because of `const`, `let`

**Comment by totherik** [comment]
Sorry, I can't justify a major release with no functional or behavioral change. There is little/no incentive for existing users to upgrade (as it currently works with v4/6 just fine) and would create a situation where minor changes/fixes would need to be backported. IMO there's not enough benefit here to warrant the extra maintenance cost. Doing this in addition to other changes that are major-rev-worthy would be acceptable, but external major rev solely based on internal housekeeping doesn't seem reasonable to me.

That said, a PR for upgrading deps would be greatly appreciated.

-Erik

**Comment by osukaa** [comment]
I'll update the PR just for updated deps

**Comment by totherik** [comment]
Separately, I think I was a bit terse so I apologize. I really appreciate you taking the time to put together the PR and contribute to this. With your change please be sure to add yourself to the `"contributors"` list in `package.json` so you get attribution for your effort. Thanks @osukaa!

**Comment by grawk** [comment]
Looks like ESLint got upgraded too far for the travis support grid

**Comment by osukaa** [comment]
Both ESLint and Hoek (probably others) latest versions are breaking because of the usage of `const` and other ES6 stuff.

I'm unsure if this PR is viable without removing 0.10/0.11/0.12 from the supported versions.

**Comment by grawk** [comment]
- we should remove 0.10 and 0.11 from the CI tests
- to avoid a major release we would need to maintain support for 0.12 and up
- If transpilation is added to the publish command, we could modify the syntax without affecting compatibility.

**Pull request closed without merging**
